# Generated by Django 4.0.4 on 2022-04-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtakapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='customer_profile/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='driver_profile/'),
        ),
    ]
