# Generated by Django 4.0.4 on 2022-04-19 16:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gtakapp', '0004_phonemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default=datetime.datetime(2022, 4, 19, 16, 32, 29, 620950, tzinfo=utc), upload_to='category_images/'),
            preserve_default=False,
        ),
    ]
